#!/bin/sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
policy_path="$repo_root/global/personal-skills-guidance.md"
skill_path="$repo_root/skills/creating-personal-skills/SKILL.md"

# AGENTS.md is generated from global/prose-style.md and the policy below.
test ! -L "$repo_root/AGENTS.md"
grep -Fq 'Generated by scripts/install-global-guidance' "$repo_root/AGENTS.md"
grep -Fq 'This repository is the only authored source' "$repo_root/AGENTS.md"
grep -Fxq '@AGENTS.md' "$repo_root/CLAUDE.md"
grep -Fq 'Never author directly in `~/.claude/skills`, `~/.claude/plugins`, or' "$policy_path"
grep -Fq '`skills/.codexignore`' "$policy_path"

grep -Fxq 'name: creating-personal-skills' "$skill_path"
grep -Eq '^description: Use when ' "$skill_path"
grep -Fq '`skills/<kebab-case-name>/`' "$skill_path"
grep -Fq '`skills/.codexignore`' "$skill_path"
grep -Fq 'skill-creator' "$skill_path"
grep -Fq 'writing-skills' "$skill_path"

printf '%s\n' 'personal skills guard tests passed'
